-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- PROFILES (Users)
create table if not exists profiles (
  id uuid references auth.users on delete cascade primary key,
  email text not null,
  display_name text,
  photo_url text,
  role text default 'متدرب' check (role in ('متدرب', 'أستاذ', 'مدير')),
  specialization text,
  phone text,
  status text default 'نشط' check (status in ('نشط', 'غير نشط')),
  must_change_password boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Add missing columns to profiles if they don't exist
do $$ 
begin 
    if not exists (select 1 from information_schema.columns where table_name='profiles' and column_name='must_change_password') then
        alter table profiles add column must_change_password boolean default false;
    end if;
end $$;

-- TEXTS (Lessons/Articles)
create table if not exists texts (
  id text primary key,
  title jsonb not null, -- { ar: string, fr: string }
  specialization jsonb not null, -- { ar: string, fr: string }
  content jsonb not null, -- { ar: string, fr: string }
  questions jsonb not null default '[]'::jsonb, -- Array of Question objects
  difficulty text default 'متوسط',
  learning_objectives jsonb default '[]'::jsonb,
  skill_ids jsonb default '[]'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Add missing columns to texts if they don't exist
do $$ 
begin 
    if not exists (select 1 from information_schema.columns where table_name='texts' and column_name='difficulty') then
        alter table texts add column difficulty text default 'متوسط';
    end if;
    if not exists (select 1 from information_schema.columns where table_name='texts' and column_name='learning_objectives') then
        alter table texts add column learning_objectives jsonb default '[]'::jsonb;
    end if;
    if not exists (select 1 from information_schema.columns where table_name='texts' and column_name='skill_ids') then
        alter table texts add column skill_ids jsonb default '[]'::jsonb;
    end if;
end $$;

-- SKILLS
create table if not exists skills (
  id bigint generated by default as identity primary key,
  title jsonb not null, -- { ar: string, fr: string }
  description jsonb not null, -- { ar: string, fr: string }
  icon_name text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- SPECIALIZATIONS
create table if not exists specializations (
  id text primary key,
  name jsonb not null, -- { ar: string, fr: string }
  trainee_count integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- TEAMS
create table if not exists teams (
  id bigint generated by default as identity primary key,
  name jsonb not null, -- { ar: string, fr: string }
  specialization jsonb not null, -- { ar: string, fr: string }
  members jsonb not null default '[]'::jsonb, -- Array of strings (names)
  presentation text, -- URL or filename
  presentation_data text,
  video_summary_url text,
  presentation_title jsonb, -- { ar: string, fr: string }
  due_date text,
  team_leader text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RESOURCES
create table if not exists resources (
  id text primary key,
  title jsonb not null, -- { ar: string, fr: string }
  type jsonb not null, -- { ar: string, fr: string }
  link text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- CHAT CHANNELS
create table if not exists chat_channels (
  id text primary key,
  name jsonb not null, -- { ar: string, fr: string }
  default_system_prompt jsonb not null,
  system_prompt jsonb not null,
  icon_name text,
  model text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- COMPLETED SKILLS (User Progress)
create table if not exists completed_skills (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  skill_id bigint references skills(id) on delete cascade not null,
  completed_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, skill_id)
);

-- PROGRESS DATA (Analytics)
create table if not exists progress_data (
  id bigint generated by default as identity primary key,
  month text not null,
  completed_texts integer default 0,
  acquired_skills integer default 0,
  test_scores integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- TEST CONTEXTS
create table if not exists test_contexts (
  id text primary key,
  title jsonb not null,
  content jsonb not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- CHAT MESSAGES
create table if not exists chat_messages (
  id bigint generated by default as identity primary key,
  channel_id text references chat_channels(id) on delete cascade not null,
  user_id uuid references profiles(id) on delete cascade, 
  role text not null check (role in ('user', 'assistant', 'system')),
  content text not null,
  timestamp timestamp with time zone default timezone('utc'::text, now()) not null,
  avatar text,
  user_name text 
);

-- ROW LEVEL SECURITY (RLS)
do $$ 
begin 
    alter table profiles enable row level security;
    alter table texts enable row level security;
    alter table skills enable row level security;
    alter table specializations enable row level security;
    alter table teams enable row level security;
    alter table resources enable row level security;
    alter table chat_channels enable row level security;
    alter table completed_skills enable row level security;
    alter table progress_data enable row level security;
    alter table test_contexts enable row level security;
    alter table chat_messages enable row level security;
exception when others then 
    null;
end $$;

-- POLICIES (Using DO blocks to avoid errors if they already exist)
do $$ 
begin 
    execute 'create policy "Public profiles are viewable by everyone" on profiles for select using (true)';
exception when others then null; end $$;

do $$ 
begin 
    execute 'create policy "Users can update own profile" on profiles for update using (auth.uid() = id)';
exception when others then null; end $$;

do $$ 
begin 
    execute 'create policy "Admins can update all profiles" on profiles for all using (exists (select 1 from profiles where id = auth.uid() and role = ''مدير''))';
exception when others then null; end $$;

-- Texts Policies
do $$ 
begin 
    execute 'create policy "Content is viewable by everyone" on texts for select using (true)';
exception when others then null; end $$;

do $$ 
begin 
    execute 'create policy "Admins can manage texts" on texts for all using (exists (select 1 from profiles where id = auth.uid() and role = ''مدير''))';
exception when others then null; end $$;

-- Simple pattern for other tables: viewable by everyone, managed by admins
do $$ 
declare
    t text;
    tables text[] := array['skills', 'specializations', 'teams', 'resources', 'chat_channels', 'test_contexts', 'progress_data'];
begin 
    foreach t in array tables loop
        begin
            execute format('create policy "%I_viewable" on %I for select using (true)', t, t);
        exception when others then null; end;
        begin
            execute format('create policy "%I_admin_manage" on %I for all using (exists (select 1 from profiles where id = auth.uid() and role = ''مدير''))', t, t);
        exception when others then null; end;
    end loop;
end $$;

-- Completed Skills
do $$ 
begin 
    execute 'create policy "Users view own completed skills" on completed_skills for select using (auth.uid() = user_id)';
exception when others then null; end $$;
do $$ 
begin 
    execute 'create policy "Users insert own completed skills" on completed_skills for insert with check (auth.uid() = user_id)';
exception when others then null; end $$;
do $$ 
begin 
    execute 'create policy "Users delete own completed skills" on completed_skills for delete using (auth.uid() = user_id)';
exception when others then null; end $$;

-- Chat Messages
do $$ 
begin 
    execute 'create policy "Messages viewable by everyone" on chat_messages for select using (true)';
exception when others then null; end $$;
do $$ 
begin 
    execute 'create policy "Users can insert messages" on chat_messages for insert with check (auth.role() = ''authenticated'')';
exception when others then null; end $$;
do $$ 
begin 
    execute 'create policy "Admins manage messages" on chat_messages for all using (exists (select 1 from profiles where id = auth.uid() and role = ''مدير''))';
exception when others then null; end $$;

-- Function to handle new user signup
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, email, display_name, photo_url)
  values (new.id, new.email, new.raw_user_meta_data->>'display_name', new.raw_user_meta_data->>'photo_url');
  return new;
end;
$$ language plpgsql security definer;

-- Trigger for new user
do $$ 
begin 
    if not exists (select 1 from pg_trigger where tgname = 'on_auth_user_created') then
        create trigger on_auth_user_created
          after insert on auth.users
          for each row execute procedure public.handle_new_user();
    end if;
end $$;
