-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- PROFILES (Users)
create table profiles (
  id uuid references auth.users on delete cascade primary key,
  email text not null,
  display_name text,
  photo_url text,
  role text default 'متدرب' check (role in ('متدرب', 'أستاذ', 'مدير')),
  specialization text,
  phone text,
  status text default 'نشط' check (status in ('نشط', 'غير نشط')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- TEXTS (Lessons/Articles)
create table texts (
  id text primary key,
  title jsonb not null, -- { ar: string, fr: string }
  specialization jsonb not null, -- { ar: string, fr: string }
  content jsonb not null, -- { ar: string, fr: string }
  questions jsonb not null default '[]'::jsonb, -- Array of Question objects
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- SKILLS
create table skills (
  id bigint generated by default as identity primary key,
  title jsonb not null, -- { ar: string, fr: string }
  description jsonb not null, -- { ar: string, fr: string }
  icon_name text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- SPECIALIZATIONS
create table specializations (
  id text primary key,
  name jsonb not null, -- { ar: string, fr: string }
  trainee_count integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- TEAMS
create table teams (
  id bigint generated by default as identity primary key,
  name jsonb not null, -- { ar: string, fr: string }
  specialization jsonb not null, -- { ar: string, fr: string }
  members jsonb not null default '[]'::jsonb, -- Array of strings (names)
  presentation text, -- URL or filename
  presentation_data text,
  video_summary_url text,
  presentation_title jsonb, -- { ar: string, fr: string }
  due_date text,
  team_leader text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RESOURCES
create table resources (
  id text primary key,
  title jsonb not null, -- { ar: string, fr: string }
  type jsonb not null, -- { ar: string, fr: string }
  link text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- CHAT CHANNELS
create table chat_channels (
  id text primary key,
  name jsonb not null, -- { ar: string, fr: string }
  default_system_prompt jsonb not null,
  system_prompt jsonb not null,
  icon_name text,
  model text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- COMPLETED SKILLS (User Progress)
create table completed_skills (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  skill_id bigint references skills(id) on delete cascade not null,
  completed_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, skill_id)
);

-- PROGRESS DATA (Analytics)
create table progress_data (
  id bigint generated by default as identity primary key,
  month text not null,
  completed_texts integer default 0,
  acquired_skills integer default 0,
  test_scores integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- TEST CONTEXTS
create table test_contexts (
  id text primary key,
  title jsonb not null,
  content jsonb not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- CHAT MESSAGES (New: Replacing localStorage)
create table chat_messages (
  id bigint generated by default as identity primary key,
  channel_id text references chat_channels(id) on delete cascade not null,
  user_id uuid references profiles(id) on delete cascade, -- Nullable if system message or anonymous
  role text not null check (role in ('user', 'assistant', 'system')),
  content text not null,
  timestamp timestamp with time zone default timezone('utc'::text, now()) not null,
  -- Additional metadata if needed
  avatar text,
  user_name text -- fallbacks if no user_id
);


-- ROW LEVEL SECURITY (RLS)
alter table profiles enable row level security;
alter table texts enable row level security;
alter table skills enable row level security;
alter table specializations enable row level security;
alter table teams enable row level security;
alter table resources enable row level security;
alter table chat_channels enable row level security;
alter table completed_skills enable row level security;
alter table progress_data enable row level security;
alter table test_contexts enable row level security;
alter table chat_messages enable row level security;

-- POLICIES

-- Profiles: Users can read all profiles (for directory) but only update their own.
create policy "Public profiles are viewable by everyone" on profiles for select using (true);
create policy "Users can update own profile" on profiles for update using (auth.uid() = id);
create policy "Admins can update all profiles" on profiles for all using (
  exists (select 1 from profiles where id = auth.uid() and role = 'مدير')
);

-- Content Tables (Texts, Skills, Resources, etc.): Public read, Admin write
create policy "Content is viewable by everyone" on texts for select using (true);
create policy "Admins can insert texts" on texts for insert with check (exists (select 1 from profiles where id = auth.uid() and role = 'مدير'));
create policy "Admins can update texts" on texts for update using (exists (select 1 from profiles where id = auth.uid() and role = 'مدير'));
create policy "Admins can delete texts" on texts for delete using (exists (select 1 from profiles where id = auth.uid() and role = 'مدير'));

-- Repeat for other content tables
-- Skills
create policy "Skills are viewable by everyone" on skills for select using (true);
create policy "Admins can manage skills" on skills for all using (exists (select 1 from profiles where id = auth.uid() and role = 'مدير'));

-- Specializations
create policy "Specializations viewable by everyone" on specializations for select using (true);
create policy "Admins manage specializations" on specializations for all using (exists (select 1 from profiles where id = auth.uid() and role = 'مدير'));

-- Teams (Assuming creating teams is restricted to admins or specific logic, for now Admin manage, everyone view)
create policy "Teams viewable by everyone" on teams for select using (true);
create policy "Admins manage teams" on teams for all using (exists (select 1 from profiles where id = auth.uid() and role = 'مدير'));

-- Resources
create policy "Resources viewable by everyone" on resources for select using (true);
create policy "Admins manage resources" on resources for all using (exists (select 1 from profiles where id = auth.uid() and role = 'مدير'));

-- Chat Channels
create policy "Channels viewable by everyone" on chat_channels for select using (true);
create policy "Admins manage channels" on chat_channels for all using (exists (select 1 from profiles where id = auth.uid() and role = 'مدير'));

-- Test Contexts
create policy "Tests viewable by everyone" on test_contexts for select using (true);
create policy "Admins manage tests" on test_contexts for all using (exists (select 1 from profiles where id = auth.uid() and role = 'مدير'));

-- Progress Data
create policy "Progress viewable by everyone" on progress_data for select using (true);
create policy "Admins manage progress" on progress_data for all using (exists (select 1 from profiles where id = auth.uid() and role = 'مدير'));

-- Completed Skills: Users can see their own, Admins see all to track progress?
-- Or "Users can see their own completed skills"
create policy "Users view own completed skills" on completed_skills for select using (auth.uid() = user_id);
create policy "Users insert own completed skills" on completed_skills for insert with check (auth.uid() = user_id);
create policy "Users delete own completed skills" on completed_skills for delete using (auth.uid() = user_id);

-- Chat Messages
-- Users can see messages in channels.
create policy "Messages viewable by everyone" on chat_messages for select using (true);
-- Users can insert messages (assuming any auth user can chat)
create policy "Users can insert messages" on chat_messages for insert with check (auth.role() = 'authenticated');
-- Admins can delete/moderate
create policy "Admins manage messages" on chat_messages for all using (exists (select 1 from profiles where id = auth.uid() and role = 'مدير'));

-- Function to handle new user signup
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, email, display_name, photo_url)
  values (new.id, new.email, new.raw_user_meta_data->>'display_name', new.raw_user_meta_data->>'photo_url');
  return new;
end;
$$ language plpgsql security definer;

-- Trigger for new user
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
